import 'package:drugdozer/domain/repositories/drug_repository.dart';
import 'package:drugdozer/domain/entities/drug.dart';
import 'package:drugdozer/domain/entities/drug_type.dart';

class DrugRepositoryImpl implements DrugRepository {
  @override
  Future<List<Drug>> getAllDrugs() async {
    return [
      ..._painRelievers(),
      ..._antibiotics(),
      ..._respiratory(),
      ..._gastrointestinal(),
      ..._allergyAndSkin(),
      ..._vitaminsAndSupplements(),
      ..._chronicAndOthers(),
    ];
  }

  @override
  Future<List<Drug>> searchDrugs(String query) async {
    final allDrugs = await getAllDrugs();
    final lowerQuery = query.toLowerCase();
    
    return allDrugs.where((drug) {
      return drug.searchKey.toLowerCase().contains(lowerQuery);
    }).toList();
  }

  @override
  Future<Drug?> getDrugById(String id) async {
    final allDrugs = await getAllDrugs();
    try {
      return allDrugs.firstWhere((drug) => drug.id == id);
    } catch (e) {
      return null;
    }
  }

  @override
  Future<List<Drug>> getDrugsByCategory(String category) async {
    final allDrugs = await getAllDrugs();
    return allDrugs.where((drug) => drug.category == category).toList();
  }

  @override
  Future<List<String>> getAllCategories() async {
    final allDrugs = await getAllDrugs();
    final categories = allDrugs.map((drug) => drug.category).toSet();
    return categories.toList();
  }

  // 1. المسكنات وخوافض الحرارة (10 أصناف)
  List<Drug> _painRelievers() {
    return [
      _createDrug(
        id: '1',
        name: 'Adol 120mg / أدول',
        category: 'مسكن وخافض حرارة',
        type: DrugType.syrup,
        concentrationMg: 120,
        concentrationMl: 5,
        minDosePerKg: 10,
        maxDosePerKg: 15,
        description: 'للأطفال والرضع.',
        warning: 'لا يتجاوز 4 جرعات يومياً.',
        howToUse: 'كل 6 ساعات عند اللزوم.',
      ),
      _createDrug(
        id: '2',
        name: 'Fevadol 160mg / فيفيدول',
        category: 'مسكن وخافض حرارة',
        type: DrugType.syrup,
        concentrationMg: 160,
        concentrationMl: 5,
        minDosePerKg: 10,
        maxDosePerKg: 15,
        description: 'خافض حرارة فعال.',
        warning: 'احذر تكرار الجرعة.',
        howToUse: 'كل 6 ساعات.',
      ),
      _createDrug(
        id: '3',
        name: 'Panadol Advance / بانادول',
        category: 'مسكن للألم',
        type: DrugType.tablet,
        fixedDose: '500-1000mg',
        description: 'للصداع وآلام الجسم.',
        warning: '8 أقراص يومياً كحد أقصى.',
        howToUse: 'قرصين كل 6 ساعات.',
      ),
      _createDrug(
        id: '4',
        name: 'Solpadiene / سولبادين',
        category: 'مسكن قوي',
        type: DrugType.tablet,
        fixedDose: 'قرص فوار',
        description: 'لآلام الأسنان والمفاصل.',
        warning: 'يسبب النعاس.',
        howToUse: 'قرص فوار كل 8 ساعات.',
      ),
      _createDrug(
        id: '5',
        name: 'Sapofen 100mg / سابوفين',
        category: 'مضاد التهاب',
        type: DrugType.syrup,
        concentrationMg: 100,
        concentrationMl: 5,
        minDosePerKg: 5,
        maxDosePerKg: 10,
        description: 'لآلام العظام والالتهابات.',
        warning: 'يؤخذ بعد الأكل.',
        howToUse: 'كل 8 ساعات.',
      ),
      _createDrug(
        id: '6',
        name: 'Catafast 50mg / كافاست',
        category: 'مسكن سريع',
        type: DrugType.tablet,
        fixedDose: 'كيس فوار',
        description: 'فوار للصداع النصفي.',
        warning: 'يمنع لمرضى الربو والحساسية.',
        howToUse: 'كيس عند اللزوم.',
      ),
      _createDrug(
        id: '7',
        name: 'Voltaren Gel / فولتارين جل',
        category: 'مسكن موضعي',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'لآلام العضلات والمفاصل.',
        warning: 'خارجي فقط.',
        howToUse: 'دهان 3 مرات يومياً.',
      ),
      _createDrug(
        id: '8',
        name: 'Ponstan Forte / بونستان',
        category: 'مسكن آلام',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'لآلام الدورة الشهرية والأسنان.',
        warning: 'يفضل بعد الطعام.',
        howToUse: 'قرص 3 مرات يومياً.',
      ),
      _createDrug(
        id: '9',
        name: 'Profinal / بروفينال',
        category: 'مسكن ومضاد التهاب',
        type: DrugType.syrup,
        concentrationMg: 100,
        concentrationMl: 5,
        minDosePerKg: 5,
        maxDosePerKg: 10,
        description: 'خافض حرارة ومسكن.',
        warning: 'يرج العبوة جيداً.',
        howToUse: 'كل 8 ساعات.',
      ),
      _createDrug(
        id: '10',
        name: 'Tempra / تيمبرا',
        category: 'خافض حرارة',
        type: DrugType.drops,
        concentrationMg: 100,
        concentrationMl: 1,
        minDosePerKg: 10,
        maxDosePerKg: 15,
        description: 'نقط للفم للرضع.',
        warning: 'دقة الجرعة مهمة.',
        howToUse: 'كل 6 ساعات.',
      ),
    ];
  }

  // 2. المضادات الحيوية (10 أصناف)
  List<Drug> _antibiotics() {
    return [
      _createDrug(
        id: '11',
        name: 'Klavox 457mg / كلافوكس',
        category: 'مضاد حيوي',
        type: DrugType.syrup,
        concentrationMg: 457,
        concentrationMl: 5,
        minDosePerKg: 25,
        maxDosePerKg: 45,
        description: 'لالتهاب التنفس والأذن.',
        warning: 'يحفظ في الثلاجة بعد الحل.',
        howToUse: 'كل 12 ساعة.',
      ),
      _createDrug(
        id: '12',
        name: 'Augmentin 625mg / أوغمنتين',
        category: 'مضاد حيوي',
        type: DrugType.tablet,
        fixedDose: 'قرص 625mg',
        description: 'مضاد بكتيري واسع الطيف.',
        warning: 'يجب إكمال الكورس.',
        howToUse: 'قرص كل 12 ساعة.',
      ),
      _createDrug(
        id: '13',
        name: 'Zinnat 250mg / زينات',
        category: 'مضاد حيوي',
        type: DrugType.tablet,
        fixedDose: 'قرص 250mg',
        description: 'للحلق واللوزتين والجلد.',
        warning: 'يؤخذ مع الطعام.',
        howToUse: 'قرص كل 12 ساعة.',
      ),
      _createDrug(
        id: '14',
        name: 'Suprax 100mg / سوبركس',
        category: 'مضاد حيوي',
        type: DrugType.syrup,
        concentrationMg: 100,
        concentrationMl: 5,
        minDosePerKg: 8,
        maxDosePerKg: 8,
        description: 'للمسالك والتهابات التنفس.',
        warning: 'مرة واحدة يومياً.',
        howToUse: 'كل 24 ساعة.',
      ),
      _createDrug(
        id: '15',
        name: 'Azomycin 200mg / آزوميسين',
        category: 'مضاد حيوي',
        type: DrugType.syrup,
        concentrationMg: 200,
        concentrationMl: 5,
        minDosePerKg: 10,
        maxDosePerKg: 10,
        description: 'كورس مضاد لـ 3 أيام.',
        warning: 'على معدة فارغة.',
        howToUse: 'مرة واحدة يومياً.',
      ),
      _createDrug(
        id: '16',
        name: 'Megamox 457mg / ميجاموكس',
        category: 'مضاد حيوي',
        type: DrugType.syrup,
        concentrationMg: 457,
        concentrationMl: 5,
        minDosePerKg: 25,
        maxDosePerKg: 45,
        description: 'بديل فعال للكلافوكس.',
        warning: 'يرج جيداً قبل الاستعمال.',
        howToUse: 'كل 12 ساعة.',
      ),
      _createDrug(
        id: '17',
        name: 'Klacid 125mg / كلاسيد',
        category: 'مضاد حيوي',
        type: DrugType.syrup,
        concentrationMg: 125,
        concentrationMl: 5,
        minDosePerKg: 7.5,
        maxDosePerKg: 15,
        description: 'التهابات الجلد والجهاز الصدري.',
        warning: 'طعم مر قليلاً.',
        howToUse: 'كل 12 ساعة.',
      ),
      _createDrug(
        id: '18',
        name: 'Curam 625mg / كيورام',
        category: 'مضاد حيوي',
        type: DrugType.tablet,
        fixedDose: 'قرص 625mg',
        description: 'لالتهابات الجهاز التنفسي.',
        warning: 'بعد الأكل لتجنب آلام المعدة.',
        howToUse: 'قرص كل 12 ساعة.',
      ),
      _createDrug(
        id: '19',
        name: 'Erythrocin 250mg / إريثروسين',
        category: 'مضاد حيوي',
        type: DrugType.tablet,
        fixedDose: 'قرص 250mg',
        description: 'بدائل البنسلين للحساسية.',
        warning: 'يؤخذ قبل الأكل بساعة.',
        howToUse: 'قرص كل 6 ساعات.',
      ),
      _createDrug(
        id: '20',
        name: 'Dalacin C / دالاسين',
        category: 'مضاد حيوي',
        type: DrugType.injection,
        fixedDose: 'حقنة واحدة',
        description: 'لحب الشباب أو الالتهابات الشديدة.',
        warning: 'حقن أو دهان حسب الوصفة.',
        howToUse: 'حسب استشارة الطبيب.',
      ),
    ];
  }

  // 3. الجهاز التنفسي والكحة (10 أصناف)
  List<Drug> _respiratory() {
    return [
      _createDrug(
        id: '21',
        name: 'Prospan / بروسبان',
        category: 'مذيب للبلغم',
        type: DrugType.syrup,
        fixedDose: '5 مل',
        description: 'مستخلص ورق اللبلاب الطبيعي.',
        warning: 'آمن للأطفال والبالغين.',
        howToUse: '5 مل 3 مرات يومياً.',
      ),
      _createDrug(
        id: '22',
        name: 'Solvin / سولفين',
        category: 'طارد للبلغم',
        type: DrugType.syrup,
        concentrationMg: 4,
        concentrationMl: 5,
        description: 'مذيب للبلغم القوي.',
        warning: 'ينصح بشرب الماء بكثرة معه.',
        howToUse: '5 مل 3 مرات يومياً.',
      ),
      _createDrug(
        id: '23',
        name: 'Ventolin Spray / فنتولين',
        category: 'موسع شعب',
        type: DrugType.spray,
        fixedDose: 'بختين',
        description: 'لأزمات الربو وضيق التنفس.',
        warning: 'قد يسبب رعشة أو زيادة نبض.',
        howToUse: 'بختين عند اللزوم.',
      ),
      _createDrug(
        id: '24',
        name: 'Sinupret / سينوبريت',
        category: 'جيوب أنفية',
        type: DrugType.syrup,
        fixedDose: 'جرعة محددة',
        description: 'شراب عشبي للجيوب الأنفية.',
        warning: 'آمن للاستخدام الطويل.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '25',
        name: 'Ezapan / إيزابان',
        category: 'كحة جافة',
        type: DrugType.syrup,
        fixedDose: '5 مل',
        description: 'مهدئ للسعال الناشف.',
        warning: 'يستخدم قبل النوم للراحة.',
        howToUse: '5 مل 3 مرات يومياً.',
      ),
      _createDrug(
        id: '26',
        name: 'Tussivan / توسيفان',
        category: 'مضاد للسعال',
        type: DrugType.syrup,
        fixedDose: '5 مل',
        description: 'للكحة الناشفة المستمرة.',
        warning: 'قد يسبب بعض الخمول.',
        howToUse: '5 مل 3 مرات يومياً.',
      ),
      _createDrug(
        id: '27',
        name: 'Rhino-P / راينو بي',
        category: 'احتقان أنف',
        type: DrugType.drops,
        fixedDose: 'نقطتين',
        description: 'نقط أنف للأطفال والرضع.',
        warning: 'لا تستخدم لأكثر من 5 أيام.',
        howToUse: 'نقطتين في كل فتحة أنف.',
      ),
      _createDrug(
        id: '28',
        name: 'Nasonex / نازونيكس',
        category: 'بخاخ أنف',
        type: DrugType.spray,
        fixedDose: 'بختين',
        description: 'لحساسية الأنف المزمنة.',
        warning: 'يحتوي على كورتيزون موضعي.',
        howToUse: 'بختين يومياً صباحاً.',
      ),
      _createDrug(
        id: '29',
        name: 'Otrivin Baby / أوترفين بيبي',
        category: 'بخاخ ملحي',
        type: DrugType.spray,
        fixedDose: 'بخة',
        description: 'لتنظيف أنف الرضع من المخاط.',
        warning: 'آمن تماماً وطبيعي.',
        howToUse: 'بخة عند اللزوم.',
      ),
      _createDrug(
        id: '30',
        name: 'Pulmicort / بولميكورت',
        category: 'تبخيرة',
        type: DrugType.drops,
        fixedDose: 'أمبولة واحدة',
        description: 'كورتيزون لجلسات البخار.',
        warning: 'يجب غسل الوجه بعد الجلسة.',
        howToUse: 'أمبولة واحدة مرتين يومياً.',
      ),
    ];
  }

  // 4. الجهاز الهضمي (10 أصناف)
  List<Drug> _gastrointestinal() {
    return [
      _createDrug(
        id: '31',
        name: 'Motilium / موتيليوم',
        category: 'مضاد للقيء',
        type: DrugType.syrup,
        concentrationMg: 1,
        concentrationMl: 1,
        minDosePerKg: 0.25,
        maxDosePerKg: 0.5,
        description: 'لعلاج الغثيان والقيء.',
        warning: 'يفضل قبل الأكل بـ 15 دقيقة.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '32',
        name: 'Gaviscon / جافيسكون',
        category: 'حموضة',
        type: DrugType.syrup,
        fixedDose: '10 مل',
        description: 'علاج ارتجاع المريء والحموضة.',
        warning: 'رج العبوة جيداً قبل الشرب.',
        howToUse: '10 مل بعد الوجبات.',
      ),
      _createDrug(
        id: '33',
        name: 'Nexium 20mg / نيكسيوم',
        category: 'قرحة المعدة',
        type: DrugType.tablet,
        fixedDose: 'قرص 20mg',
        description: 'حماية المعدة من الأحماض.',
        warning: 'يؤخذ على الريق صباحاً.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '34',
        name: 'Buscopan / بسكوبان',
        category: 'تقلصات',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'لعلاج المغص والتقلصات.',
        warning: 'قد يسبب جفاف الفم.',
        howToUse: 'قرص 3 مرات يومياً.',
      ),
      _createDrug(
        id: '35',
        name: 'Flagyl 200mg / فلاجيل',
        category: 'مطهّر معوي',
        type: DrugType.syrup,
        concentrationMg: 200,
        concentrationMl: 5,
        minDosePerKg: 30,
        maxDosePerKg: 50,
        description: 'لعلاج الإسهال والطفيليات.',
        warning: 'يجب إكمال المدة المقررة.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '36',
        name: 'Antinal / أنتينال',
        category: 'إسهال بكتيري',
        type: DrugType.syrup,
        concentrationMg: 220,
        concentrationMl: 5,
        description: 'مطهّر معوي واسع المدى.',
        warning: 'آمن للأطفال والرضع.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '37',
        name: 'Maalox / مالوكس',
        category: 'مضاد حموضة',
        type: DrugType.syrup,
        fixedDose: 'ملعقة',
        description: 'شراب لحرقان المعدة.',
        warning: 'يفصل عن الأدوية الأخرى بساعتين.',
        howToUse: 'ملعقة عند اللزوم.',
      ),
      _createDrug(
        id: '38',
        name: 'Dulcolax / دولكولاكس',
        category: 'ملين',
        type: DrugType.tablet,
        fixedDose: 'قرصين',
        description: 'لعلاج الإمساك الحاد.',
        warning: 'لا يستخدم لفترة طويلة.',
        howToUse: 'قرصين قبل النوم.',
      ),
      _createDrug(
        id: '39',
        name: 'Imodium / إيموديوم',
        category: 'مضاد إسهال',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'يوقف حركة الأمعاء الزائدة.',
        warning: 'ليس للإسهال البكتيري.',
        howToUse: 'قرص عند اللزوم.',
      ),
      _createDrug(
        id: '40',
        name: 'Duspatalin / دوسباتالين',
        category: 'قولون عصبي',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'مهدئ لتقلصات القولون.',
        warning: 'يبلع كاملاً بدون كسر.',
        howToUse: 'قبل الأكل بـ 20 دقيقة.',
      ),
    ];
  }

  // 5. الحساسية والجلد (10 أصناف)
  List<Drug> _allergyAndSkin() {
    return [
      _createDrug(
        id: '41',
        name: 'Zyrtec / زيرتك',
        category: 'مضاد حساسية',
        type: DrugType.syrup,
        concentrationMg: 5,
        concentrationMl: 5,
        minDosePerKg: 0.25,
        maxDosePerKg: 0.5,
        description: 'للحكة، الرشح والعطاس.',
        warning: 'قد يسبب بعض النعاس.',
        howToUse: 'مرة واحدة قبل النوم.',
      ),
      _createDrug(
        id: '42',
        name: 'Fenistil Drops / فينيستيل',
        category: 'نقط حساسية',
        type: DrugType.drops,
        concentrationMg: 1,
        concentrationMl: 1,
        minDosePerKg: 2,
        maxDosePerKg: 2,
        description: 'علاج حساسية الجلد واللدغ.',
        warning: 'يسبب خمول للأطفال.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '43',
        name: 'Fucidin Cream / فوسيدين',
        category: 'مضاد حيوي جلدي',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'علاج الجروح والحبوب الملتهبة.',
        warning: 'للاستخدام الخارجي فقط.',
        howToUse: 'دهان 3 مرات يومياً.',
      ),
      _createDrug(
        id: '44',
        name: 'Mebo / ميبو',
        category: 'كريم حروق',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'لترميم الجلد وعلاج الحروق.',
        warning: 'يتميز برائحة السمسم.',
        howToUse: 'كل 4 ساعات على الحرق.',
      ),
      _createDrug(
        id: '45',
        name: 'Claritine / كلاريتين',
        category: 'مضاد حساسية',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'مضاد حساسية لا يسبب النعاس.',
        warning: 'فعال لمدة 24 ساعة.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '46',
        name: 'Differin Gel / ديفرين',
        category: 'حب الشباب',
        type: DrugType.cream,
        fixedDose: 'مسحة رقيقة',
        description: 'تقشير البشرة وعلاج الحبوب.',
        warning: 'يستخدم ليلاً فقط بعيداً عن الضوء.',
        howToUse: 'مسحة رقيقة على الحبوب.',
      ),
      _createDrug(
        id: '47',
        name: 'Canesten / كانيستين',
        category: 'مضاد فطريات',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'علاج الفطريات الجلدية والقدم.',
        warning: 'يجب الاستمرار عليه بانتظام.',
        howToUse: 'دهان مرتين يومياً.',
      ),
      _createDrug(
        id: '48',
        name: 'Bepanthen / بيبانثين',
        category: 'مرطب جلد',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'مرطب للبشرة الحساسة والإكزيما.',
        warning: 'آمن جداً للأطفال.',
        howToUse: 'عند الحاجة.',
      ),
      _createDrug(
        id: '49',
        name: 'Tobradex / توبرادكس',
        category: 'قطرة عين',
        type: DrugType.drops,
        fixedDose: 'قطرة',
        description: 'مضاد حيوي وكورتيزون للعين.',
        warning: 'لا تلمس طرف القطارة بالعين.',
        howToUse: 'قطرة 4 مرات يومياً.',
      ),
      _createDrug(
        id: '50',
        name: 'Systane Ultra / سيستان',
        category: 'مرطب عين',
        type: DrugType.drops,
        fixedDose: 'قطرة',
        description: 'علاج جفاف العين الشديد.',
        warning: 'ترج العبوة قبل الاستعمال.',
        howToUse: 'عند اللزوم.',
      ),
    ];
  }

  // 6. فيتامينات ومكملات (10 أصناف)
  List<Drug> _vitaminsAndSupplements() {
    return [
      _createDrug(
        id: '51',
        name: 'Neurobion / نيوروبيون',
        category: 'فيتامين ب',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'لدعم الأعصاب وعلاج الضعف.',
        warning: 'مفيد جداً لمرضى السكري.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '52',
        name: 'Osteocare / أوستوكير',
        category: 'كالسيوم',
        type: DrugType.syrup,
        fixedDose: '10 مل',
        description: 'لدعم العظام والأسنان والنمو.',
        warning: 'لا يؤخذ مع مكملات الحديد.',
        howToUse: '10 مل يومياً.',
      ),
      _createDrug(
        id: '53',
        name: 'Centrum / سنتروم',
        category: 'فيتامينات',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'مكمل غذائي شامل للجسم.',
        warning: 'يفضل بعد وجبة الغداء.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '54',
        name: 'Feroglobin / فيروجلوبين',
        category: 'حديد ومعادن',
        type: DrugType.syrup,
        fixedDose: '5 مل',
        description: 'لعلاج فقر الدم (الأنيميا).',
        warning: 'قد يغير لون البراز للأسود.',
        howToUse: '5 مل يومياً.',
      ),
      _createDrug(
        id: '55',
        name: 'Seven Seas / سفن سيز',
        category: 'أوميجا 3',
        type: DrugType.syrup,
        fixedDose: '5 مل',
        description: 'زيت كبد الحوت الغني بالفيتامينات.',
        warning: 'يقوي المناعة والقدرة الذهنية.',
        howToUse: '5 مل يومياً.',
      ),
      _createDrug(
        id: '56',
        name: 'Perfectil / بيرفكتيل',
        category: 'فيتامين للشعر',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'لصحة الشعر والأظافر والجلد.',
        warning: 'يؤخذ على معدة ممتلئة فقط.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '57',
        name: 'Vitamin D3 / فيتامين د',
        category: 'فيتامينات',
        type: DrugType.tablet,
        fixedDose: 'حسب الطبيب',
        description: 'لرفع مستويات نقص فيتامين د.',
        warning: 'يؤخذ مع وجبة دسمة لزيادة الامتصاص.',
        howToUse: 'حسب وصف الطبيب.',
      ),
      _createDrug(
        id: '58',
        name: 'Pharmaton / فارماتون',
        category: 'مكمل طاقة',
        type: DrugType.tablet,
        fixedDose: 'كبسولة',
        description: 'لعلاج الإجهاد وزيادة التركيز.',
        warning: 'يحتوي على الجينسينج.',
        howToUse: 'كبسولة بعد الإفطار.',
      ),
      _createDrug(
        id: '59',
        name: 'Redoxon / ريدوكسون',
        category: 'فيتامين سي',
        type: DrugType.tablet,
        fixedDose: 'قرص فوار',
        description: 'فوار لتقوية المناعة.',
        warning: 'امتصاص سريع وفعال.',
        howToUse: 'قرص فوار يومياً.',
      ),
      _createDrug(
        id: '60',
        name: 'Genuphil / جينوفيل',
        category: 'مفاصل',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'علاج خشونة المفاصل والتهابها.',
        warning: 'يحتاج استمرارية لـ 3 أشهر.',
        howToUse: '3 مرات يومياً.',
      ),
    ];
  }

  // 7. أدوية مزمنة ومتنوعة (40 صنف - الوصول لـ 100)
  List<Drug> _chronicAndOthers() {
    return [
      _createDrug(
        id: '61',
        name: 'Glucophage 500 / جلوكوفاج',
        category: 'منظم سكر',
        type: DrugType.tablet,
        fixedDose: 'حسب الطبيب',
        description: 'سكري النوع الثاني.',
        warning: 'يؤخذ وسط الأكل.',
        howToUse: 'حسب الوصفة.',
      ),
      _createDrug(
        id: '62',
        name: 'Janumet / جانوميت',
        category: 'علاج السكري',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'خافض سكر مركب قوي.',
        warning: 'قد يسبب اضطراب معدة.',
        howToUse: 'مرتين يومياً.',
      ),
      _createDrug(
        id: '63',
        name: 'Concor 5mg / كونكور',
        category: 'ضغط وقلب',
        type: DrugType.tablet,
        fixedDose: 'قرص 5mg',
        description: 'لتنظيم ضربات القلب والضغط.',
        warning: 'لا توقفه فجأة أبداً.',
        howToUse: 'صباحاً.',
      ),
      _createDrug(
        id: '64',
        name: 'Exforge / إكسفورج',
        category: 'علاج الضغط',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'علاج ضغط الدم المرتفع.',
        warning: 'يراقب تورم القدمين.',
        howToUse: 'مرة يومياً.',
      ),
      _createDrug(
        id: '65',
        name: 'Lipitor 20mg / ليبيتور',
        category: 'كوليسترول',
        type: DrugType.tablet,
        fixedDose: 'قرص 20mg',
        description: 'خافض للدهون الضارة.',
        warning: 'يفضل استخدامه ليلاً.',
        howToUse: 'قبل النوم.',
      ),
      _createDrug(
        id: '66',
        name: 'Crestor 10mg / كريستور',
        category: 'كوليسترول',
        type: DrugType.tablet,
        fixedDose: 'قرص 10mg',
        description: 'علاج ارتفاع الكوليسترول.',
        warning: 'يراقب وظائف الكبد.',
        howToUse: 'مرة ليلاً.',
      ),
      _createDrug(
        id: '67',
        name: 'Euthyrox / إيوتيروكس',
        category: 'غدة درقية',
        type: DrugType.tablet,
        fixedDose: 'حسب الطبيب',
        description: 'بديل هرمون الغدة الدرقية.',
        warning: 'على الريق تماماً.',
        howToUse: 'قبل الإفطار بـ 30 دقيقة.',
      ),
      _createDrug(
        id: '68',
        name: 'Daflon 500 / دافلون',
        category: 'أوعية دموية',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'بواسير ودوالي الساقين.',
        warning: 'يؤخذ بعد الأكل بانتظام.',
        howToUse: 'حسب الحالة.',
      ),
      _createDrug(
        id: '69',
        name: 'Viagra 50mg / فياجرا',
        category: 'مقوي',
        type: DrugType.tablet,
        fixedDose: 'قرص 50mg',
        description: 'علاج الضعف الجنسي.',
        warning: 'تحت إشراف طبي فقط.',
        howToUse: 'قبل اللقاء بساعة.',
      ),
      _createDrug(
        id: '70',
        name: 'Cialis 5mg / سياليس',
        category: 'مقوي',
        type: DrugType.tablet,
        fixedDose: 'قرص 5mg',
        description: 'ضعف الانتصاب والبروستاتا.',
        warning: 'يؤخذ يومياً بنفس الموعد.',
        howToUse: 'قرص يومياً.',
      ),
      _createDrug(
        id: '71',
        name: 'Vominore / فومينور',
        category: 'غثيان الحمل',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'علاج غثيان الصباح للحوامل.',
        warning: 'قد يسبب النعاس.',
        howToUse: 'قبل النوم.',
      ),
      _createDrug(
        id: '72',
        name: 'Enterogermina / انتروجرمينا',
        category: 'بكتيريا نافعة',
        type: DrugType.drops,
        fixedDose: 'أمبولة',
        description: 'توازن بكتيريا الأمعاء.',
        warning: 'شرب للأمبولة.',
        howToUse: 'أمبولة واحدة يومياً.',
      ),
      _createDrug(
        id: '73',
        name: 'Stugeron 25 / ستوجيرون',
        category: 'دوار ودوخة',
        type: DrugType.tablet,
        fixedDose: 'قرص 25mg',
        description: 'علاج طنين الأذن والدوار.',
        warning: 'يسبب خمول ونعاس.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '74',
        name: 'Rennie / ريني',
        category: 'حموضة',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'أقراص للمضغ سريعة المفعول.',
        warning: 'آمن للحامل.',
        howToUse: 'عند اللزوم.',
      ),
      _createDrug(
        id: '75',
        name: 'Strepsils / ستربسلز',
        category: 'آلام حلق',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'أقراص استحلاب للحلق.',
        warning: 'لا تبلع الحبة.',
        howToUse: 'كل 3 ساعات.',
      ),
      _createDrug(
        id: '76',
        name: 'Vicks VapoRub / فيكس',
        category: 'دهان منشط',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'لتخفيف البرد والاحتقان.',
        warning: 'خارجي فقط.',
        howToUse: 'دهان على الصدر والظهر.',
      ),
      _createDrug(
        id: '77',
        name: 'Glycerin / جليسرين رضع',
        category: 'ملين',
        type: DrugType.injection,
        fixedDose: 'تحميلة',
        description: 'تحاميل للإمساك عند الرضع.',
        warning: 'مفعول سريع.',
        howToUse: 'عند اللزوم.',
      ),
      _createDrug(
        id: '78',
        name: 'Diclac 75mg / ديكلاك',
        category: 'مسكن عظام',
        type: DrugType.injection,
        fixedDose: 'حقنة',
        description: 'حقن مسكنة قوية جداً.',
        warning: 'بالعضل فقط.',
        howToUse: 'عند الألم الشديد.',
      ),
      _createDrug(
        id: '79',
        name: 'Betadine / بيتادين',
        category: 'مطهّر',
        type: DrugType.drops,
        fixedDose: 'كمية مناسبة',
        description: 'تعقيم الجروح والحروق.',
        warning: 'للاستخدام الخارجي.',
        howToUse: 'عند اللزوم.',
      ),
      _createDrug(
        id: '80',
        name: 'Dewax / ديواكس',
        category: 'شمع أذن',
        type: DrugType.drops,
        fixedDose: '3 نقط',
        description: 'إذابة شمع الأذن المتصلب.',
        warning: 'لا تستخدم للثقب.',
        howToUse: '3 نقط مرتين يومياً.',
      ),
      _createDrug(
        id: '81',
        name: 'Loceryl / لوسيريل',
        category: 'فطريات أظافر',
        type: DrugType.drops,
        fixedDose: 'طلاء',
        description: 'طلاء طبي للفطريات.',
        warning: 'يجب برد الظفر أولاً.',
        howToUse: 'مرة أو مرتين أسبوعياً.',
      ),
      _createDrug(
        id: '82',
        name: 'Cyclo-Progynova / سيكلو',
        category: 'تنظيم هرمونات',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'تنظيم الدورة الشهرية.',
        warning: 'اتبع ترتيب الحبوب.',
        howToUse: 'قرص يومياً.',
      ),
      _createDrug(
        id: '83',
        name: 'Ventolin Solution / محلول',
        category: 'محلول نيبولايزر',
        type: DrugType.drops,
        fixedDose: 'حسب الوزن',
        description: 'لجلسات جهاز البخار.',
        warning: 'يخفف بمحلول ملح.',
        howToUse: 'حسب الوزن.',
      ),
      _createDrug(
        id: '84',
        name: 'Amaryl / أماريل',
        category: 'خافض سكر',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'علاج السكري.',
        warning: 'يؤخذ قبل الإفطار.',
        howToUse: 'مرة واحدة يومياً.',
      ),
      _createDrug(
        id: '85',
        name: 'Plavix / بلافيكس',
        category: 'مسيل للدم',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'منع التجلطات القلبية.',
        warning: 'يحدد الطبيب المدة.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '86',
        name: 'Aspirin 100mg / أسبرين',
        category: 'وقاية قلبية',
        type: DrugType.tablet,
        fixedDose: 'قرص 100mg',
        description: 'سيولة الدم والوقاية.',
        warning: 'يؤخذ بعد الأكل.',
        howToUse: 'قرص واحد يومياً.',
      ),
      _createDrug(
        id: '87',
        name: 'Lasix 40mg / لازكس',
        category: 'مدر بول',
        type: DrugType.tablet,
        fixedDose: 'قرص 40mg',
        description: 'تفريغ سوائل الجسم الزائدة.',
        warning: 'يراقب البوتاسيوم.',
        howToUse: 'صباحاً فور الاستيقاظ.',
      ),
      _createDrug(
        id: '88',
        name: 'Atacand 16mg / أتاكاند',
        category: 'علاج الضغط',
        type: DrugType.tablet,
        fixedDose: 'قرص 16mg',
        description: 'علاج ضغط الدم.',
        warning: 'قد يسبب كحة جافة.',
        howToUse: 'مرة واحدة يومياً.',
      ),
      _createDrug(
        id: '89',
        name: 'Aldomet 250mg / ألدوميت',
        category: 'ضغط حامل',
        type: DrugType.tablet,
        fixedDose: 'قرص 250mg',
        description: 'علاج الضغط أثناء الحمل.',
        warning: 'آمن جداً للجنين.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '90',
        name: 'Elocom Cream / إيلوكوم',
        category: 'حساسية جلد',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'كورتيزون قوي للالتهاب.',
        warning: 'استخدام لفترة قصيرة.',
        howToUse: 'دهان مرة واحدة يومياً.',
      ),
      _createDrug(
        id: '91',
        name: 'Baneocin / بانيوسين',
        category: 'مضاد حيوي',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'بودرة أو كريم للجروح.',
        warning: 'جروح سطحية ملتهبة.',
        howToUse: 'دهان مرتين يومياً.',
      ),
      _createDrug(
        id: '92',
        name: 'Kenacomb / كيناكومب',
        category: 'كريم شامل',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'بكتيريا، فطريات وحساسية.',
        warning: 'يحتوي على كورتيزون.',
        howToUse: 'دهان مرتين يومياً.',
      ),
      _createDrug(
        id: '93',
        name: 'Daktarin Oral Gel / داكتارين',
        category: 'فطريات فم',
        type: DrugType.cream,
        fixedDose: 'كمية صغيرة',
        description: 'جل لعلاج فطريات اللسان.',
        warning: 'لا يبلع فوراً للفعالية.',
        howToUse: '4 مرات يومياً.',
      ),
      _createDrug(
        id: '94',
        name: 'Gaviscon Advance / جافيسكون',
        category: 'ارتجاع قوي',
        type: DrugType.syrup,
        fixedDose: '10 مل',
        description: 'قوة مضاعفة للارتجاع.',
        warning: 'بعد الوجبات مباشرة.',
        howToUse: '10 مل.',
      ),
      _createDrug(
        id: '95',
        name: 'Brufen 400mg / بروفين',
        category: 'مسكن آلام',
        type: DrugType.tablet,
        fixedDose: 'قرص 400mg',
        description: 'آلام الأسنان والمفاصل.',
        warning: 'بعد الأكل لتجنب القرحة.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '96',
        name: 'Zovirax / زوفيراكس',
        category: 'كريم هربس',
        type: DrugType.cream,
        fixedDose: 'طبقة رقيقة',
        description: 'لعلاج الهربس الفيروسي.',
        warning: 'دهان موضعي فقط.',
        howToUse: '5 مرات يومياً.',
      ),
      _createDrug(
        id: '97',
        name: 'Fludrex / فلوودركس',
        category: 'برد وزكام',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'علاج أعراض الرشح والحرارة.',
        warning: 'يسبب نعاس واضح.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '98',
        name: 'Panadol Night / بانادول ليلة',
        category: 'مسكن منوم',
        type: DrugType.tablet,
        fixedDose: 'قرصين',
        description: 'مسكن آلام يساعد على النوم.',
        warning: 'يؤخذ قبل النوم فقط.',
        howToUse: 'قرصين قبل النوم.',
      ),
      _createDrug(
        id: '99',
        name: 'Spasmonal / سباسمونال',
        category: 'قولون',
        type: DrugType.tablet,
        fixedDose: 'قرص',
        description: 'مضاد لتشنج الأمعاء والقولون.',
        warning: 'يفضل قبل الأكل.',
        howToUse: '3 مرات يومياً.',
      ),
      _createDrug(
        id: '100',
        name: 'Heptamyl / هيبتاميل',
        category: 'رفع الضغط',
        type: DrugType.drops,
        fixedDose: 'حسب الحاجة',
        description: 'علاج ضغط الدم المنخفض.',
        warning: 'قد يسبب نشاط زائد.',
        howToUse: 'عند اللزوم.',
      ),
    ];
  }

  // Helper method to create Drug objects
  Drug _createDrug({
    required String id,
    required String name,
    required String category,
    required DrugType type,
    double concentrationMg = 0,
    double concentrationMl = 0,
    double minDosePerKg = 0,
    double maxDosePerKg = 0,
    required String description,
    required String warning,
    required String howToUse,
    String? fixedDose,
  }) {
    // Extract Arabic and English names
    String arabicName = name;
    String englishName = name;
    
    if (name.contains('/')) {
      final parts = name.split('/');
      englishName = parts.first.trim();
      arabicName = parts.last.trim();
    }
    
    return Drug(
      id: id,
      name: name,
      arabicName: arabicName,
      englishName: englishName,
      category: category,
      type: type,
      concentrationMg: concentrationMg,
      concentrationMl: concentrationMl,
      minDosePerKg: minDosePerKg,
      maxDosePerKg: maxDosePerKg,
      description: description,
      warning: warning,
      howToUse: howToUse,
      fixedDose: fixedDose,
    );
  }
}